In [ ]:
import numpy

In [ ]:

arr=numpy.array([1,2,3])
print(arr)
print(type(arr))

[1 2 3]
<class 'numpy.ndarray'>


# for comment


In [ ]:
l=[1,2,3, 'python']
print(l)
print(type(l))

[1, 2, 3, 'python']
<class 'list'>


In [ ]:
arr=numpy.array([[1,2,3, 'python']])
print(arr)
print(type(arr))

[1.  2.5 3. ]
<class 'numpy.ndarray'>


In [ ]:
arr=numpy.array([])
print(arr)
print(type(arr))

[]
<class 'numpy.ndarray'>


In [ ]:
l = []
print(l)
print(type(l))

[]
<class 'list'>


Types of Array:
1D
2D
N dimensional



To find the dimension we use size (no of elements)
 array_name.ndim
 array_name.size

In [ ]:
arr=numpy.array([1, 2, 3])
print(arr)
print(type(arr))
print("size=",arr.size)
print("shape=",arr.shape)

[1 2 3]
<class 'numpy.ndarray'>
size= 3
shape= (3,)


In [ ]:
print(arr.ndim)

1


In [ ]:
a = numpy.array([ [1,2,3] ])
print( a.ndim )
print(a)
print("size=",a.size)
print("shape=",a.shape)

2
[[1 2 3]]
size= 3
shape= (1, 3)


In [ ]:
a = numpy.array([ [1,2,3], [4,5,6]])
print( a.ndim )
print(a)
print("size=",a.size)
print("shape=",a.shape)

2
[[1 2 3]
 [4 5 6]]
size= 6
shape= (2, 3)


In [ ]:
import numpy as np

In [ ]:
a = np.array([ [1,2,3], [4,5,6] ])
print( a.shape )
print(a)


(2, 3)
[[1 2 3]
 [4 5 6]]


In [ ]:
b = a.reshape(1,6)
print(b)

[[1 2 3 4 5 6]]


In [ ]:
arr = np.array([1,2,3,4,5])

TypeError: array() takes from 1 to 2 positional arguments but 5 were given

In [ ]:
import numpy as np
a = np.arange(12)
print(a.ndim)
print(a)

1
[ 0  1  2  3  4  5  6  7  8  9 10 11]


Arange

In [ ]:
import numpy as np
a = np.arange(1, 15, 2)
print(a.ndim)
print(a)
b= a.reshape(-1, 1)
print(b)
print(b.ndim)
print(b.shape)

1
[ 1  3  5  7  9 11 13]
[[ 1]
 [ 3]
 [ 5]
 [ 7]
 [ 9]
 [11]
 [13]]
2
(7, 1)


Always use:
reshape(1,-1)
or
reshape(-1,1)

to convert 1D into 2D array

In [ ]:
import numpy as np
a = np.arange(1, 15, 2)
print(a.ndim)
print(a)
b= a.reshape(1, -1)
print(b)
print(b.ndim)
print(b.shape)

1
[ 1  3  5  7  9 11 13]
[[ 1  3  5  7  9 11 13]]
2
(1, 7)


Operations on array:


In [ ]:
import numpy as np
a = np.array([ [1,2,3], [4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
b = np.array([[1,2], [4,5], [6,7]])
print(b)

[[1 2]
 [4 5]
 [6 7]]


In [ ]:
print("Addition")
print(a+b)

Addition
[[ 2  4  6]
 [ 8 10 12]]


In [ ]:
print("Subtraction")
print(a-b)

Subtraction
[[0 0 0]
 [0 0 0]]


In [ ]:
print("Division")
print(a/b)



Division
[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
print("Multiplication")
print(a*b)

Multiplication
[[ 1  4  9]
 [16 25 36]]


Matrices:



In [ ]:
m1 = np.mat(a)
print(m1)
print(type(m1))

[[1 2 3]
 [4 5 6]]
<class 'numpy.matrix'>


In [ ]:
m2 = np.matrix([[1,2], [4,5], [6,7]])
print(m2)
print(type(m2))

[[1 2]
 [4 5]
 [6 7]]
<class 'numpy.matrix'>


In [ ]:
print("mul")
print(m1*m2)

mul
[[27 33]
 [60 75]]


In [ ]:
c = np.dot(a,b)
print(c)

[[27 33]
 [60 75]]
