In [ ]:
import numpy as np

In [ ]:
arr = np.arange(10)
print(arr)
print(type(arr))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [ ]:
arr = np.arange(2,20,3)
print(arr)
print(type(arr))

[ 2  5  8 11 14 17]
<class 'numpy.ndarray'>


Operations arithmetic & statistical on Array

In [ ]:
array = np.arange(10)
print(array)
print(type(array))
print(array.sum())

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
45


In [ ]:
print(array.mean())


4.5


In [ ]:
print(array.max())
print(array.min())
print(array.tolist())
print(array.std())

9
0
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
2.8722813232690143


All 1's & 0's

In [ ]:
zero = np.zeros([2,3], dtype =int)
print(zero)
print(type(zero))

[[0 0 0]
 [0 0 0]]
<class 'numpy.ndarray'>


In [ ]:
one = np.ones([4,5], dtype =int)
print(one)
print(type(one))

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
<class 'numpy.ndarray'>


In [ ]:
one = np.ones([4,5], dtype =int)
a = one * 30
print("Array with value as 30")
print(a)
print(type(a))

Array with value as 30
[[30 30 30 30 30]
 [30 30 30 30 30]
 [30 30 30 30 30]
 [30 30 30 30 30]]
<class 'numpy.ndarray'>


In [ ]:

o= np.full((2, 3), 5)
print(o)

[[5 5 5]
 [5 5 5]]


Create an identity matrix -

In [ ]:
a = np.eye(4, dtype = int)
print(a)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [ ]:
b = np.diag([10, 5, 30])
print(b)
print(type(b))

[[10  0  0]
 [ 0  5  0]
 [ 0  0 30]]
<class 'numpy.ndarray'>


Random numbers

In [ ]:
from numpy import random
x = random.randint(1000)
print(x)


486


In [ ]:
import numpy.random as np
x = np.randint(10000)
print(x)
print(type(x))

935


In [ ]:
import numpy.random as np
import numpy as np1
x = np.randint(10000, size = (5))
print(x)
print(type(x))

[4248 6788  615 1148  240]
<class 'numpy.ndarray'>


In [ ]:
x = np.rand()
print(x)

0.2646520603073047


In [ ]:
x = np.randn()
print(x)

0.05819296939489666


In [ ]:
import numpy as np1
A=np1.array([1,2,3,4,5,6,7])
B=np1.array([2,5,7,8,9])
A
B
print(np1.intersect1d(A,B))
print(np1.setdiff1d(A,B))
print(np1.setdiff1d(B,A))

[2 5 7]
[1 3 4 6]
[8 9]
